### PR TITLE
Remove `daysback` option

### PR DESCRIPTION
**Pull request by hoechenberger**
Anonymization should happen on the BIDS level.

Closes GH-159.

### CODE REVIEW

**Comment by hoechenberger** [comment]
CI fails:
```
RuntimeError: info[meas_id][secs] must be between "-2147483648" and "2147483647", got "-5364627420"
```

I remember, there was this issue with the previous anonymization approach in old datasets…

**Comment by hoechenberger** [comment]
I first thought this was related to https://github.com/mne-tools/mne-python/pull/7711 but it's probably sth else

**Comment by hoechenberger** [comment]
I guess we'll just re-anonymize the dataset and push it to OpenNeuro? However I don't have write access to the [`ds000246` repo](https://openneuro.org/datasets/ds000246)

It says "uploaded by Julia Guiomar Niso Galán" -- anyone know how I could get in touch to ask for creation of a new revision, or for access rights to publish it myself?

**Comment by agramfort** [comment]
yes data needs to be fixed on openneuro

**Comment by jasmainak** [comment]
ping @guiomar

@hoechenberger can you articulate what exactly is the problem with the dataset for the benefit of @guiomar ?

**Comment by hoechenberger** [comment]
@jasmainak I just dropped her an email 😃 So my understanding of the issue is that, in essence, the dataset was anonymized with an older version of MNE, and newer versions have difficulties dealing with that. We need to re-anonymize the dataset with MNE 0.20 to fix the problem.

**Comment by jasmainak** [comment]
I doubt it was anonymized with MNE. Maybe with brainstorm ...

**Comment by agramfort** [comment]
it was anonymized with brainstorm but using older convention of the bids
standard

>

**Comment by guiomar** [comment]
Hi! If I correctly remember we did a face mask on T1w MRI (using open tool Face Masking, http://nrg.wustl.edu/software/face-masking (Milchenko and Marcus 2013)) and anonymize the acquisition date by adding a random number of hours (different for each subject but the same for each scan within a subject) as suggested by the BIDS spec at that time (1.0.2).

Happy to upload the new version.
(I also ping @ftadel just in case)

**Comment by agramfort** [comment]
regarding acq_time this issue is that fif files cannot store dates that are
too old. We had to change the valid acq_time in BIDS anonymized files to
make it fif compatible.

**Comment by guiomar** [comment]
Ok, I see! Thank you Alex

**Comment by guiomar** [comment]
By the way, do you know if this has been updated to the BIDS spec?
This is what is now on the scans.tsv:
https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file
I guess is this same parameter value (acq_time) which is inside the fif and ds files, right?

**Comment by agramfort** [comment]
@sappelhoff @jasmainak can you help me point to the right section in the bids standard?
yes to me it's the acq_time parameter

**Comment by sappelhoff** [comment]
The "anonymization" rule details in BIDS were changed in November 2019, see: https://github.com/bids-standard/bids-specification/pull/363 ... based on the discussion in this issue: https://github.com/bids-standard/bids-specification/issues/360

The only change was:

```diff
To distinguish real dates from shifted dates always use year
-1900
+1925
or earlier when including shifted years.
```

So I guess @agramfort is right with what he said in https://github.com/mne-tools/mne-study-template/pull/160#issuecomment-659389921 ... the data was probably anonymized to some date prior to 1900 ... and this now trips up the FIF file format, which can only store dates that are a bit later (not prior 1900)

**Comment by jasmainak** [comment]
what I don't understand is how brainstorm deals with dates before 1900. @guiomar must have checked that the files can be read after anonymizing.

**Comment by jasmainak** [comment]
just to be sure @hoechenberger are you dealing with fif files or CTF files?

**Comment by sappelhoff** [comment]
they are `.ds` files as it seems :shrug:

**Comment by guiomar** [comment]
Thanks a lot @sappelhoff!!
I can't recall if we did that anonymizaton with Bst or with CTF software. Anyways, I guess that maybe for .ds files is not as problematic as for fif. That may be why we could work with them without problems.

**Comment by jasmainak** [comment]
so CTF files are not subject to the same int32 issues as fif, it might be an MNE issue ...

**Comment by agramfort** [comment]
the pb comes when you save any fif file starting from the CTF ds file
(new raw, epochs, evoked etc).

**Comment by jasmainak** [comment]
oh boy ...

**Comment by guiomar** [comment]
Thanks! Then if this is the case, BIDS should enforce to to use a year 1925, and remove the "or earlier" from the specs.
As it doesn't make sense to allow something that won't be compatible with all the file formats. Or at least make a note, so people can decide knowing it, specially in the MEG field. I think it could be useful.

**Comment by jasmainak** [comment]
> Then if this is the case, BIDS should enforce to to use a year 1925, and remove the "or earlier" from the specs.

The problem is that in longitudinal studies, people want to keep the relative time. So if you had recordings over 5 years, they want to keep this information.

but I agree that the 1925 year limit is too stringent. It doesn't make pragmatic sense and will hinder adoption of BIDS in MEG community

**Comment by jasmainak** [comment]
According to [HHS regulations](https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html), you only need to anonymize up to a year:

> (C) All elements of dates (except year) for dates that are directly related to an individual, including birth date, admission date, discharge date, death date, and all ages over 89 and all elements of dates (including year) indicative of such age, except that such ages and elements may be aggregated into a single category of age 90 or older

**Comment by sappelhoff** [comment]
You can always do a PR to bids-standard/bids-specification to insert a note that alerts people to the fact that "choosing a very early date (e.g., 1880) will negatively affect interoperability. --> because FIF does not support it.

AFAIK this is not a problem for any other data format.

**Comment by guiomar** [comment]
Thanks! I think I'll do :)
Just out of curiosity, what's the limit to crash the fif?

**Comment by sappelhoff** [comment]
> Just out of curiosity, what's the limit to crash the fif?

I think @alexrockhill looked into this deeply at some point.

**Comment by jasmainak** [comment]
some date in 1901 :)

it's basically 1st January 1970 - number of seconds that can be represented by int32 (=2,147,483,647)

**Comment by alexrockhill** [comment]
The datetime is stored in fif as a 16-bit integer which when converted into seconds before/after Jan 1, 1970 (time = 0) ranges from 1919 to 2040 or so (the numbers aren't exact) that's why we had to ask BIDS to move the anonymization date required up from before 1900 to before 1925.

**Comment by guiomar** [comment]
Thanks a lot!!

**Comment by hoechenberger** [comment]
Closed via #257

**Pull request closed without merging**
