### PR TITLE
TESTS: Retrieve somato dataset from OSF

### PR DESCRIPTION
**Pull request by hoechenberger**
This is MUCH faster than downloading it from GitHub and should, therefore, speed up CI testing quite a bit.

### CODE REVIEW

**Comment by agramfort** [comment]
data should be cached by circleci anyway it's a price to pay only once

**Comment by hoechenberger** [comment]
> data should be cached by circleci anyway it's a price to pay only once

But I can see how it's taking a long time to download almost every single time we run those tests… and when I run the test data download locally or on `drago4`, it starts out fast but then after a while starts crawling super slowly, I think this might be an issue with `git-annex` on GitHub with many files small files or something

**Comment by agramfort** [comment]
circle caching does not work?

>

**Comment by hoechenberger** [comment]
> data should be cached by circleci anyway it's a price to pay only once

Caching seems to only happen within any given Circle run, not across subsequent runs. Since we're only using each dataset once during each CI run, we don't profit from caching

**Comment by hoechenberger** [comment]
> circle caching does not work?

Not as far as I can tell, it's downloading all data in each new run

**Comment by agramfort** [comment]
then it's the first thing to do. Enable caching in circleci like we do in
MNE.

**Comment by hoechenberger** [comment]
> then it's the first thing to do. Enable caching in circleci like we do in
> MNE.

Ok will look into this. But this would still not help for local testing :)

**Pull request closed without merging**
