### PR TITLE
Maxfilter first: addresses issue #59

### PR DESCRIPTION
**Pull request by SophieHerbst**
Here is a suggestion on how to reverse the order of Maxfilter and frequency filter:
 
**01-import_and_maxfilter.py**
- import data
- set up BIDS derivatives
- Maxfilter if config says so
- save sss or nosss file (the latter prevents us from doing the import again in Script 02 if maxfilter is not applied)

**02-frequency_filter**
- read each run and apply frequency filters

I also put a link in Readme to explain how to obtain sample in BIDS (issue #62)

_[Unfortunately, the PR displays the changes only from Script 01 -> 02, while from 02 -> 01 is presented as a completely new file. If there is a way to change this retrospectively, let me know.]_

### CODE REVIEW

**Comment by SophieHerbst** [comment]
Argh (re: circleci error). I did not follow the description in contributing, because installing git-annex failed on my Mac. Can this be fixed?

**Comment by agramfort** [comment]
@SophieHerbst so far so good. Can you see why CIs complain?

**Comment by jasmainak** [comment]
> I did not follow the description in contributing, because installing git-annex failed on my Mac. Can this be fixed?

arghgh ... it is indeed a pain. I gave up myself.

**Comment by SophieHerbst** [comment]
good to know @jasmainak, however it wasn't what caused the CIs to fail.  
I have no idea how to fix this: 
`RuntimeError: info["meas_date"] seconds must be between "(-2147483648, 0)" and "(2147483647, 0)", got "-5364627420"`

**Comment by jasmainak** [comment]
It seems like an MNE problem. It broke in this pull request: https://github.com/mne-tools/mne-python/pull/7016. The culprit is yet again @bloyl. I don't know why he tries to keep sabotaging MNE hmmmm :)

**Comment by agramfort** [comment]
thx @SophieHerbst 

let's iterate now.

**Pull request merged**
