### PR TITLE
mixed formatting and doc improvements

### PR DESCRIPTION
**Pull request by sappelhoff**
minor changes while I was going through the codebase.

Points I noticed:
- It is unclear how to get the MRI data for the "example" described in the README
- The "example" data on OSF contains an empty `system calibration files` directory in `LocalizerDATA` ... is this an error?

### CODE REVIEW

**Comment by jasmainak** [comment]
MRI documentation is kind of sparse in MNE as well :-)

maybe you can adapt this somehow: 

https://github.com/mne-tools/mne-biomag-group-demo/blob/master/scripts/processing/01-anatomy.py ?

**Comment by agramfort** [comment]
no objection to merge but FYI the readme file is not really up to date as we use here sample. The readme comes from this fork. https://github.com/brainthemind/CogBrainDyn_MEG_Pipeline

**Comment by sappelhoff** [comment]
Okay, but is this `master`? Or has that fork now become `master`?

Where should I primarily work so that I don't cause conflicts?

Feel free to merge

**Comment by agramfort** [comment]
don't worry. Nothing is released yet. We can do things manually later. Make
it work. We'll make it nice later

>

**Comment by sappelhoff** [comment]
cc @jasmainak 

this one can be merged I believe

**Comment by jasmainak** [comment]
Merged, moving on to more serious contributions ;)

**Comment by sappelhoff** [comment]
yes! perhaps you could review https://github.com/bids-standard/bids-validator/pull/789? it's blocking https://github.com/mne-tools/mne-bids/pull/209

**Pull request merged**
