### PR TITLE
Default high-pass of 0.1 Hz, unify phrasing

### PR DESCRIPTION
**Pull request by hoechenberger**
This PR changes the default high-pass filter cutoff from 1.0 Hz to 0.1 Hz, as 1.0 Hz seems a little high to me. What do you think?

### CODE REVIEW

**Comment by jasmainak** [comment]
For ICA you will need 1 Hz

**Comment by hoechenberger** [comment]
> For ICA you will need 1 Hz

Yes but we filter again for ICA anyway, see
https://github.com/mne-tools/mne-study-template/blob/ee8e1740a6ce41a6ef780646c4b7622bfa679fd5/04a-run_ica.py#L74-L75



> did you look at the rendered artifacts? can you share the old and new versions so we can eyeball the plots?

Yes will do.

**Comment by hoechenberger** [comment]
> Yes but we filter again for ICA anyway, see

I will rework the code to reduce duplication and make things more clear, will ping you when ready.

**Comment by hoechenberger** [comment]
This has been superseded by #237, which sets `l_freq=None`.

**Pull request closed without merging**
