### PR TITLE
Remove MEG fine-cal & crosstalk config options

### PR DESCRIPTION
**Pull request by hoechenberger**
We can now find these files thanks to the BIDS specification.

Re-enable ds000248 tests, thanks to @agramfort who managed to update the
dataset.

### CODE REVIEW

**Comment by agramfort** [comment]
I think we need to wait for datalad to get the new version or we download with openneuro cli

**Comment by hoechenberger** [comment]
Let's hope the sync works…

**Comment by hoechenberger** [comment]
@sappelhoff `matchingpennies` is now the only dataset we're not retrieving from OpenNeuro. Care to publish it there? :) This would allow us to simplify our test setup, now that we have [`openneuro-py`](https://github.com/hoechenberger/openneuro-py).

**Comment by hoechenberger** [comment]
@jasmainak I've switched all OpenNeuro dataset downloads to [`openneuro-py`](https://github.com/hoechenberger/openneuro-py), meaning we won't need `datalad` for those anymore!

**Comment by jasmainak** [comment]
lovely, and I see you managed to do it without dependency on `awscli` (although there is an unnecessary dependency on `click` :P)

**Comment by hoechenberger** [comment]
> although there is an unnecessary dependency on `click` :P

You guys never want to take advantage of stuff that makes your life easier, eh? 😅😜

**Comment by hoechenberger** [comment]
@agramfort It passes!! Good to merge

**Comment by agramfort** [comment]
thanks @hoechenberger !

**Comment by sappelhoff** [comment]
>  Care to publish it there?

I am afraid I can't do that:
1. I think having the dataset on one service provider is more clear
1. openneuro datasets are licensed under CC0, but eeg_matchingpennies already has an ODBL license
1. the eeg_matchingpennies dataset *is* subject to the GDPR, so uploading to openneuro is not permitted

but that probably means that we cannot use eeg_matchingpennies in the study template anymore, right?

PS: cool work!

**Comment by hoechenberger** [comment]
> 3\. the eeg_matchingpennies dataset _is_ subject to the GDPR, so uploading to openneuro is not permitted

You sure about this? If the data is anonymized, I don't think it should be a problem. When collecting research data, participants consent to anonymized publication, so this should all be covered.

**Comment by hoechenberger** [comment]
> but that probably means that we cannot use eeg_matchingpennies in the study template anymore, right?

We can, it just adds some overhead because it's the only dataset that needs to be fetched via data datalad

**Comment by hoechenberger** [comment]
> > 3. the eeg_matchingpennies dataset _is_ subject to the GDPR, so uploading to openneuro is not permitted
> 
> You sure about this? If the data is anonymized, I don't think it should be a problem. When collecting research data, participants consent to anonymized publication, so this should all be covered.

Also… how come it's okay to publish this on GitHub, then? I must be missing something here?

**Comment by sappelhoff** [comment]
> You sure about this?

unsure and insecure enough to not want to go that direction - and I don't wanna wake sleeping dogs with such a move.

image

> how come it's okay to publish this on GitHub, then? I must be missing something here?

it's mirrored on GitHub via git annex links --> the data is all on OSF, if you clone from GitHub all you are getting is the information on where to get the real data. (datalad/git-annex magic)

> We can, it just adds some overhead because it's the only dataset that needs to be fetched via data datalad

perhaps we'll have to find a good EEG dataset alternative then, I totally see the advantage of not doing workarounds just to accommodate a single dataset.

**Comment by hoechenberger** [comment]
> perhaps we'll have to find a good EEG dataset alternative then, I totally see the advantage of not doing workarounds just to accommodate a single dataset.

We could just dump a Zip somewhere and download that using curl / wget? Would this work with OSF?

**Comment by sappelhoff** [comment]
You *can* select the `eeg_matchingpennies` folder on https://osf.io/cj2dr/ and click download as zip --> but a brief investigation didn't show me a way to construct a generic link for that without clicking.

Also, it'd download the whole dataset, which may be undesirable if all you need is just one subject.

image

**Comment by hoechenberger** [comment]
@sappelhoff Looks like it's time for … osf-py! 

https://developer.osf.io/#

😅😳😭😜

**Pull request merged**
