### PR TITLE
trigger circle

### PR DESCRIPTION
**Pull request by massich**
does it work?

### CODE REVIEW

**Comment by massich** [comment]
Circle is not trigger

**Comment by larsoner** [comment]
I enabled builds on `circleci.com`, but for some reason it's still not building. Not sure why

**Comment by jasmainak** [comment]
maybe you need a circle.yml file?

**Comment by jasmainak** [comment]
oh you have it already ...

**Comment by larsoner** [comment]
The problem was that the file had no workflows, see the fix in:

https://github.com/mne-tools/mne-study-template/commit/363f6727f4a126046e936c85769be373623a79c2

And running here:

https://circleci.com/gh/mne-tools/mne-study-template/1

**Pull request closed without merging**
