### PR TITLE
missing reject_tmax from config

### PR DESCRIPTION
**Pull request by agramfort**
see https://mne.tools/mne-biomag-group-demo/auto_scripts/library/config.html#sphx-glr-auto-scripts-library-config-py

where it was used @hoechenberger

### CODE REVIEW

**Comment by hoechenberger** [comment]
Interesting, I didn't know about this parameter :)

Why did you change highpass fiktering, though? Is it not a good idea to high-pass by default?

**Comment by agramfort** [comment]
@hoechenberger regarding high-pass I think it's a dangerous default to set it to 1Hz. Maybe 0.3 Hz would be a better default but I think it's better to use simple baselines using pre-stim data by default. Of course we should look at rendered reports to see if data say otherwise and if so maybe we set the l_freq != None in the config of those datasets

**Comment by hoechenberger** [comment]
You're right, 1 Hz highpass is too high. Ok let's try with None and see how well it works!

**Review by hoechenberger — APPROVED** [review]

**Comment by agramfort** [comment]
looks good https://1766-167957354-gh.circle-artifacts.com/0/site/examples/ds000248.html

**Comment by hoechenberger** [comment]
Nice!

**Pull request merged**
