### PR TITLE
Use anonymized "somato" dataset; adjust for upstream MNE-BIDS changes

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
Test is failing because the new OpenNeuro dataset is not yet available from GitHub:
github.com/OpenNeuroDatasets/ds003104

**Comment by agramfort** [comment]
maybe wait 24h then

**Comment by hoechenberger** [comment]
It's still not there. I think there's something off. Will get in touch with the OpenNeuro folks.

**Comment by hoechenberger** [comment]
Just for the record, I've dropped them an email, waiting for a response now. The dataset is still not on GitHub.

**Comment by hoechenberger** [comment]
@agramfort merge if you're happy. The dataset is now fully functional.

**Comment by agramfort** [comment]
Thx @hoechenberger

**Pull request merged**
