### PR TITLE
WIP: Add documentation

### PR DESCRIPTION
**Pull request by hoechenberger**
Let's see how this turns out…

### CODE REVIEW

**Comment by agramfort** [comment]
why is CI not running here ? :(

**Comment by hoechenberger** [comment]
No clue :( Maybe I broke sth in the config, but I linted the file and it seems clean

**Comment by hoechenberger** [comment]
https://status.circleci.com/incidents/bkjyrv8fj1rg

**Comment by hoechenberger** [comment]
Build artifact:
https://793-167957354-gh.circle-artifacts.com/0/site/index.html

**Comment by hoechenberger** [comment]
CircleCI artifact web server doesn't seem to deliver `index.html` by default, so here are links to the artifacts>


https://793-167957354-gh.circle-artifacts.com/0/site/index.html
https://793-167957354-gh.circle-artifacts.com/0/site/settings/index.html

**Pull request merged**
