### PR TITLE
[MRG] Re-arrange scripts directory, add split "sensor" scripts into "preprocessing" and "sensor", change how individual steps can be run

### PR DESCRIPTION
**Pull request by hoechenberger**
This PR moves the scripts into separate subdirectories:

```shell
$ tree scripts
scripts
├── 01-preprocessing
│   ├── 01-import_and_maxfilter.py
│   ├── 02-frequency_filter.py
│   ├── 03-make_epochs.py
│   ├── 04a-run_ica.py
│   ├── 04b-run_ssp.py
│   ├── 05a-apply_ica.py
│   └── 05b-apply_ssp.py
├── 02-sensor_level
│   ├── 01-make_evoked.py
│   ├── 02-sliding_estimator.py
│   ├── 03-time_frequency.py
│   └── 04-group_average_sensors.py
├── 03-source_level
│   ├── 01-make_forward.py
│   ├── 02-make_cov.py
│   ├── 03-make_inverse.py
│   └── 04-group_average_source.py
└── 04-reports
    └── 01-make_reports.py

4 directories, 16 files
```
I have separated the steps that were previously only referred to as "sensor" into "preprocessing" and "sensor".
The option to run a script by specifying its step number to `run.py` is gone; instead, you can now specify the "group" and step name, e.g.:

```
run.py preprocessing/run_ica
```
I think this is more intuitive than before!

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
good move !

**Comment by hoechenberger** [comment]
Relevant doc artifact:
https://1146-167957354-gh.circle-artifacts.com/0/site/features/steps.html

**Comment by hoechenberger** [comment]
Hang on with merging want to change a few details

**Comment by agramfort** [comment]
sure. merge when you are ready

>

**Pull request merged**
