### PR TITLE
MRG: Same namig scheme for regular & fsaverage STC

### PR DESCRIPTION
**Pull request by hoechenberger**
Closes GH-81.

STC naming for a sample participant:

```
sub-CC110033_inverse-dSPM-audiovis1200Hz-fsaverage-lh.stc
sub-CC110033_inverse-dSPM-audiovis1200Hz-fsaverage-rh.stc
sub-CC110033_inverse-dSPM-audiovis1200Hz-lh.stc
sub-CC110033_inverse-dSPM-audiovis1200Hz-rh.stc
```

WDYT?

### CODE REVIEW

**Comment by jasmainak** [comment]
So BIDS names are typically key-value pairs separated by underscores. I'd suggested sticking to something like that as it allows you to use tools like `pybids` to parse the files and get useful info. Of course, there is no file naming for derivatives but it would help to follow similar conventions to see what we can benefit from it

**Comment by hoechenberger** [comment]
> So BIDS names are typically key-value pairs separated by underscores. I'd suggested sticking to something like that

Yes that's what I've been trying to do here, actually :)

```
sub-CC110033_inverse-dSPM-audiovis1200Hz-fsaverage-rh.stc
```
Only thing I could imagine to change is maybe to separate the last part too? i.e.,
```
sub-CC110033_inverse-dSPM-audiovis1200Hz_fsaverage-rh.stc
```
?

**Comment by jasmainak** [comment]
What about

```py
sub-CC110033_inverse-dSPM_task-audiovis1200Hz_fsaverage-rh.stc
```

?

**Comment by hoechenberger** [comment]
Hmm… not bad. How about:
```
sub-CC110033_task-task_cond-audiovis1200Hz_inverse-dSPM_fsaverage-rh.stc
```
Or based on your proposal:
Hmm… not bad. How about:
```
sub-CC110033_inverse-dSPM_task-task_cond-audiovis1200Hz_fsaverage-rh.stc
```
It's really difficult and the filenames get ridiculously long…

**Comment by jasmainak** [comment]
Right, so you might want to look at BEP03 (more complete) and BEP021 (very much a draft) in your free time. The basic principles for derivatives are outlined there. I remember there was a long discussion on how to create derivative filenames. One suggestion was to use the source filename and append the processing information at the end. This has the problem that filenames start getting ridiculously long as you say. The other suggestion was to use just say `label-variant1` and `label-variant2` and then have an accompanying json file which has the info about the parameters used in these variants.

Anyway, I guess for now you could probably use something like:

```sh
<source_filename>_cond-audiovis1200Hz_inverse-dSPM_fsaverage-rh.stc
```

?

**Comment by hoechenberger** [comment]
> ```shell
> ```shell
> <source_filename>_cond-audiovis1200Hz_inverse-dSPM_fsaverage-rh.stc
> ```
> 
> 
> ? where <source_filename> is everything excluding _meg.<ext>
>       
> ```

Ok, so with my example dataset this would actually correspond to my first proposal:

> ```
sub-CC110033_task-task_cond-audiovis1200Hz_inverse-dSPM_fsaverage-rh.stc
> ```

Will look into this tomorrow. And thanks for the reading suggestions!

**Comment by hoechenberger** [comment]
@SophieHerbst Do you have any opinion on this? How's your experience working with such long filenames?

**Comment by hoechenberger** [comment]
This is what I've come up with:

Individual participant:
```
sub-CC110033_task-task_cond-audiovis1200Hz_inverse-dSPM_hemi-lh.stc
report_task-task.html
```

Group:
```
average_task-task_cond-audiovis1200Hz_inverse-dSPM_morph-fsaverage_hemi-lh.stc
report_average_task-task.html
```

This seems to be KINDA consistent and is certainly an improvement compared to where we were coming from. I would therefore like to propose to merge this PR as soon as CI goes green, and iterate in followup PRs if needed. (And maybe have a quick discussion about which naming scheme(s) to adopt)

**Comment by agramfort** [comment]
I like that !

>

**Comment by hoechenberger** [comment]
Also I'd like to add:
The number of repetitive code blocks is increasing. We should pick up discussion on how to deal with this issue soon, before the code base becomes more and more difficult to maintain.

**Comment by agramfort** [comment]
Thx @hoechenberger

**Pull request merged**
