### PR TITLE
WIP: Parallelize CI runs

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by agramfort** [comment]
this suggests that each build should then use it's own data cache

**Comment by hoechenberger** [comment]
(I fscking hate YAML…)

**Comment by agramfort** [comment]
We get use to it:)

You certainly have a linter for circle Ci files

**Comment by hoechenberger** [comment]
> You certainly have a linter for circle Ci files

hm yes but it says [right there](https://support.circleci.com/hc/en-us/articles/360006735753-Validating-your-CircleCI-Configuration):

> Note: local-cli does not validate workflows at this time

And we need to use workflows for parallelism… but yeah maybe I can validate the rest of the file, the workflow section is actually quite short…

**Pull request closed without merging**
