### PR TITLE
Try report

### PR DESCRIPTION
**Pull request by massich**
This should break.

### CODE REVIEW

**Comment by massich** [comment]
yes this does segfault in the circle config.

Reverting `TST: 99-report`

**Comment by sappelhoff** [comment]
@massich what was the intent of this PR?

**Comment by massich** [comment]
This PR was showing that report was failing. I agree that the codebase has diverged.

**Comment by sappelhoff** [comment]
> This PR was showing that report was failing. I agree that the codebase has diverged.

It's still failing for me locally - do we know more about why? Are there fix PRs on the way somewhere?

**Comment by jasmainak** [comment]
What is the error you see?

**Comment by sappelhoff** [comment]
coming from `make all`:

```Shell
python 99-make_reports.py
Processing sample
Embedding : jquery-1.10.2.min.js
Embedding : jquery-ui.min.js
Embedding : bootstrap.min.js
Embedding : jquery-ui.min.css
Embedding : bootstrap.min.css
Iterating over 35 potential files (this may take some time)
Rendering : /home/stefanappelhoff/mne_data/MNE-sample-data/MEG/sample/all-trans.fif
Using outer_skin.surf for head surface.
Getting helmet for system 306m
Makefile:37: recipe for target 'report' failed
make: *** [report] Segmentation fault (core dumped)

```

**Comment by jasmainak** [comment]
Ahh, this is a mayavi issue :-) I think there is an open PR in MNE for this: https://github.com/mne-tools/mne-python/pull/5894

**Comment by massich** [comment]
This should be solved in master by https://github.com/mne-tools/mne-python/pull/6433 maybe we should port it to `v.18.2`

**Comment by massich** [comment]
https://github.com/mne-tools/mne-python/pull/6452

**Comment by sappelhoff** [comment]
closing, because the codebase has moved considerably. This is now tracked in #47

**Pull request closed without merging**
