### PR TITLE
[MRG] add EEG_matchingpennies to testing data

### PR DESCRIPTION
**Pull request by sappelhoff**
To do:

- [x] merge #42 through "rebase and merge" option

### CODE REVIEW

**Comment by jasmainak** [comment]
Looks good!

**Comment by jasmainak** [comment]
can you rebase now @sappelhoff ?

**Comment by sappelhoff** [comment]
done @jasmainak

**Comment by jasmainak** [comment]
Merged, thanks @sappelhoff !

**Comment by jasmainak** [comment]
@sappelhoff can you help me finish the other two PRs #43 and #41 ? You can push directly to my branch (let me know if you don't have permission)

**Comment by sappelhoff** [comment]
sure, let me take a look at it :+1:

**Comment by agramfort** [comment]
Magic how little lines you need for a new dataset :)

We should have one dataset that also does make source and ideally make report we could see as artifact on circle

**Pull request merged**
