### PR TITLE
Add config.get_subject_path(), config.get_subject_deriv_path()

### PR DESCRIPTION
**Pull request by hoechenberger**
The common task of creating the path to the directory where the data is stored for a particular participant & recording kind has now been moved into the `config.get_subject_path()` function.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Now looking at this again, we could even consider introducing a function `get_deriv_path()`...

**Comment by agramfort** [comment]
do what you feel is best

**Comment by hoechenberger** [comment]
Ok let's see what CI says

**Comment by hoechenberger** [comment]
I love it when the diff shows a negative net difference of the line count :-)

**Pull request merged**
