### PR TITLE
RF: Do sensor-level group average via mne.grand_average()

### PR DESCRIPTION
**Pull request by hoechenberger**
This works thanks to a fix in `mne-python:master` that will be included in 0.19: https://github.com/mne-tools/mne-python/pull/6711

So this PR should probably only be merged after `mne-python` 0.19 has been released?

### CODE REVIEW

**Comment by agramfort** [comment]
thx @hoechenberger 

this breaks a test though. 2 options:
- fix mne
- fix the code here by avoiding to call grand_average if there is only one evoked

**Comment by hoechenberger** [comment]
@agramfort Yeah I just saw that too. Didn't catch this locally because I couldn't download the sample dataset (slow connection). Will look into this. I think the [assertion](https://github.com/mne-tools/mne-python/blob/34bd8b605b459da3cbb2b2657862ed09c16fdfcb/mne/utils/numerics.py#L579) that more than 1 instance should be passed to `mne.grand_average()` _does_ make sense though. But I also believe that grand averaging should, ideally, be done using the `grand_average()` function, just because the name is very explicit :) – How can it happen that we end up with a list of length 1 here anyway? Oh well, need to fetch the sample data once I have time and step through the pipeline.

**Comment by agramfort** [comment]
you have only one subject in this dataset

>

**Comment by hoechenberger** [comment]
Ok, so I was thinking, and I believe since this template also serves as some kind of reference, it would be great to use `mne.granda_average()` here as, like I said, the name is verbose, and because it sets `.nave` to the "correct" value.

So how about we modify `mne.grand_average()` to
- raise if the input sequence is empty
- throw a warning if the input sequence length is 1
- proceed as usual otherwise

Can open an issue on the mne-python issue tracker to discuss this, of course.

**Comment by jasmainak** [comment]
@hoechenberger why do you want to change something that works? is there any advantage to use `mne.grand_average` ?

**Comment by agramfort** [comment]
I guess it's a matter of documenting what is more recommended. I would
agree that mne.grand_average is really meant for this operation (group
level average of sensor data).

I am inclined to relax the constraint that mne.grand_average requires more
than one evoked and just raise a warning in this case.

ok for you @jasmainak ?

**Comment by hoechenberger** [comment]
@jasmainak, like @agramfort said:
> I guess it's a matter of documenting what is more recommended.

That's exactly my point here :)

**Comment by jasmainak** [comment]
sounds good, this would need a PR to mne-python in that case

**Comment by hoechenberger** [comment]
@jasmainak Will do next week :)

**Comment by hoechenberger** [comment]
… Or next month. Haha. Will put this on my todo list.

**Comment by agramfort** [comment]
success ! merging

**Comment by hoechenberger** [comment]
Yay! Thanks for your help

**Pull request merged**
